# Generated by Django 5.2.9 on 2026-02-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0067_remove_nixchannel_pgpubsub_ae5b1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nixmaintainer',
            name='github',
            field=models.CharField(max_length=200),
        ),
    ]
