# Generated by Django 5.2.14 on 2026-07-03 07:30

from django.db import migrations, models


def populate_variant(apps, schema_editor):
    NixChannel = apps.get_model("shared", "NixChannel")
    for channel in NixChannel.objects.all():
        if channel.channel_branch.endswith("-small"):
            channel.variant = "small"
        elif channel.channel_branch.endswith("-darwin"):
            channel.variant = "darwin"
        elif channel.channel_branch.startswith("nixos-"):
            channel.variant = "primary"
        channel.save(update_fields=["variant"])


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0096_alter_cvederivationclusterproposal_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nixchannel',
            name='variant',
            field=models.CharField(choices=[('primary', 'primary'), ('small', 'small'), ('darwin', 'darwin')], max_length=126, null=True),
        ),
        # The table has triggers registered.
        # Altering it within the migration will defer them to after the transaction, thus failing the whole thing.
        migrations.RunSQL("ALTER TABLE shared_nixchannel DISABLE TRIGGER USER"),
        migrations.RunPython(
            code=populate_variant,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunSQL("ALTER TABLE shared_nixchannel ENABLE TRIGGER USER"),
    ]
