# Generated by Django 5.2.14 on 2026-07-02 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0097_nixchannel_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageClusterProposalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provenance_flags', models.IntegerField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cve_links', to='shared.package')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_links', to='shared.cvederivationclusterproposal')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('proposal', 'package'), name='unique_package_per_proposal')],
            },
        ),
    ]
