# Generated by Django 5.2.15 on 2026-07-13 10:27

import pgtrigger.migrations
import shared.models.cve
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0098_add_package_cluster_proposal_link'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='cpe',
            name='cpe_search_vector_idx',
        ),
        migrations.RemoveIndex(
            model_name='cpe',
            name='shared_cpe_search__347dd9_gin',
        ),
        migrations.RemoveField(
            model_name='cpe',
            name='search_vector',
        ),
        migrations.AlterField(
            model_name='cpe',
            name='name',
            # This is fine, there are no `None` values in production.
            field=models.CharField(default='', max_length=2048, validators=[shared.models.cve.validate_cpe]),
            preserve_default=False,
        ),
    ]
