# Generated by Django 5.2.17 on 2026-10-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0103_nixderivationmeta_cpe_identifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nixchannel',
            name='head_sha1_commit',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='nixevaluation',
            name='commit_sha1',
            field=models.CharField(max_length=40),
        ),
        migrations.AddConstraint(
            model_name='nixchannel',
            constraint=models.CheckConstraint(condition=models.Q(('head_sha1_commit__regex', '^[0-9a-f]{40}$')), name='nixchannel_head_sha1_commit_valid'),
        ),
        migrations.AddConstraint(
            model_name='nixevaluation',
            constraint=models.CheckConstraint(condition=models.Q(('commit_sha1__regex', '^[0-9a-f]{40}$')), name='nixevaluation_commit_sha1_valid'),
        ),
    ]
