# Generated by Django 5.2.17 on 2026-10-07 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0106_backfill_packageoverlay_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageoverlay',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='overlays', to='shared.package'),
        ),
        migrations.AddField(
            model_name='packageoverlayevent',
            name='package',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='shared.package'),
        ),
    ]
